apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  type: NodePort
  selector:
    app: ghost
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ghsot-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/ghost"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
        tier: frontend
    spec:
      containers:
      - image: ghost:latest
        name: website
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 2368
            protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /ghost/api/admin/site/
        #     port: http
        #     httpHeaders:
        #       - name: X-Forwarded-Proto
        #         value: https
        # livenessProbe:
        #   initialDelaySeconds: 60
        #   httpGet:
        #     path: /ghost/api/admin/site/
        #     port: http
        #     httpHeaders:
        #       - name: X-Forwarded-Proto
        #         value: https
        resources:
          requests:
            memory: '128Mi'
            cpu: '100m'
          limits:
            memory: '256Mi'
            cpu: '150m'
        env:
          - name: NODE_ENV
            value: production
          - name: database__client
            value: mysql
          - name: database__connection__host
            value: ghost-mysql
          - name: database__connection__user
            value: ghost_user
          - name: database__connection__password
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: userpassword
          - name: database__connection__database
            value: ghost_db
          - name: logging__transports
            value: '["stdout"]'
          - name: logging__level
            value: info
          - name: url
            value: http://blog.niiadu.com
          - name: mail__transport
            value: SMTP
          - name: mail__options__service
            value: Mailgun
          - name: mail__options__auth__user
            valueFrom:
              secretKeyRef:
                name: ghost-pass
                key: smtp_username
          - name: mail__options__auth__pass
            valueFrom:
              secretKeyRef:
                name: ghost-pass
                key: smtp_password
        volumeMounts:
          - name: ghost-persistent-storage
            mountPath: /var/www/html
      volumes:
        - name: ghost-persistent-storage
          persistentVolumeClaim:
            claimName: ghost-pv-claim